/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import org.realaxy.kinect.porter.tests.kinect.KinectUserSerializeTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var org_realaxy_kinect_porter_tests_kinect_KinectUserSerializeTest_obj:org.realaxy.kinect.porter.tests.kinect.KinectUserSerializeTest;
	}
}